### ISSUE TITLE
Issue with catalogue api

### ISSUE THREAD

**Issue by vulovicv23** [mrt1m/playstation-store-api#1]
Hey! First of all thank you for the library, it is awesome that you built this.

Im having issues with catalogue api, this is the curl of what im sending:

`curl --location -g 'https://web.np.playstation.com/api/graphql/v1/op?operationName=categoryGridRetrieve&variables={%22id%22%3A%2244d8bb20-653e-431e-8ad0-c0a365f68d2f%22%2C%22pageArgs%22%3A{%22size%22%3A10%2C%22offset%22%3A0}%2C%22sortBy%22%3A{%22name%22%3A%22productReleaseDate%22%2C%22isAscending%22%3Afalse}%2C%22filterBy%22%3A[]%2C%22facetOptions%22%3A[]}&extensions={%22persistedQuery%22%3A{%22version%22%3A1%2C%22sha256Hash%22%3A%22cb5765103b5294add90a887683722f662e751fb7c3b944b63bc117127485d570%22}}' \
--header 'Host: web.np.playstation.com' \
--header 'x-psn-store-locale-override: en-US' \
--header 'Cookie: _abck=60FE12DF55263C134A398FD1336040B8~-1~YAAQmnnKFyKaaeaGAQAAlS6K9AmbtPJ0co6bCW4iUliH0wcJOSQlmPX+svYzq33rOZlQN9VRNJLFV8Oaepv9mjp01ImfjlGrm/GRNOobuVf/0/JdW3rEAOAq8BI6rXUuOhsoUehDTNY68PsQ+sHRS27XRcCZJnwj0yHDJmRKJSHBAa/pz4RCBmWH6coi4gLEn8w5sm7QtGn+JkiYG7utgzIxn+iQzqkFGQjmx77IHirVNW7y5eZI9WG4kJwPc4YIvDnY8bmMnUi+9NPWiwc9w/8/kDA5NBt6qT8+NvINsMuWfmwwmdcorlW3wPOc2GST/ruG12wO5J38u5LDVzTTXZyPtvsGY9Y5u+FRmyFIeGnJP/o/iR31cPLe8xGK8Ca7V8s0rOkquObGa/cqqKZMKtMyjeNfxRmF5psPYDXbE302~-1~-1~-1; bm_sz=C68C3B30CB4BAC2046DCA0C07C3AD7A5~YAAQmnnKF7KFaeaGAQAABDWE9BOoAFSMlLNNE83D2YuuAd6HDhjwA4K8PuRfyu4y3nJ5q78kC+Ph4wKcZUiU25bW6BIemQPnTJSeWGHg3hBCAipEDLf3kkHRhn6+a14KvblItOHei0YdAffHyVkIw362cHn68fdmtu7H/NZDnB0AvNPeECt6iG775p+mD9YajDvnDjgELOoDcftwQpzDNvvMjJ2jcpfX3AlJx6n9KDDjj1j0WelTbsQHhz/lEE8H3OFCjvBqvPhtALpuCOWlH2zjuuSbwgrDrBCUgC+yggPDntizTLuLCllgOtdhATk7dMXQtu+uEx+clI940SCkiYFqan9HieI5QNPOLHsPzej1LDve+cvo/JINoDI6Wsz/xu12E6ceXA==~4470067~4605492'`

And the response for that is:

`{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'operation')"
        }
    ]
}`

Can you help me out?

**Comment by mrt1m** [comment]
Hi, current api isn’t stable. Now I am working for second version package where all data get from graphql api.18.03.2023, 16:47, "Vukasin Vulovic" ***@***.***>:
Hey! First of all thank you for the library, it is awesome that you built this.
Im having issues with catalogue api, this is the curl of what im sending:
curl --location -g 'https://web.np.playstation.com/api/graphql/v1/op?operationName=categoryGridRetrieve&variables={%22id%22%3A%2244d8bb20-653e-431e-8ad0-c0a365f68d2f%22%2C%22pageArgs%22%3A{%22size%22%3A10%2C%22offset%22%3A0}%2C%22sortBy%22%3A{%22name%22%3A%22productReleaseDate%22%2C%22isAscending%22%3Afalse}%2C%22filterBy%22%3A[]%2C%22facetOptions%22%3A[]}&extensions={%22persistedQuery%22%3A{%22version%22%3A1%2C%22sha256Hash%22%3A%22cb5765103b5294add90a887683722f662e751fb7c3b944b63bc117127485d570%22}}' \ --header 'Host: web.np.playstation.com' \ --header 'x-psn-store-locale-override: en-US' \ --header 'Cookie: _abck=60FE12DF55263C134A398FD1336040B8~-1~YAAQmnnKFyKaaeaGAQAAlS6K9AmbtPJ0co6bCW4iUliH0wcJOSQlmPX+svYzq33rOZlQN9VRNJLFV8Oaepv9mjp01ImfjlGrm/GRNOobuVf/0/JdW3rEAOAq8BI6rXUuOhsoUehDTNY68PsQ+sHRS27XRcCZJnwj0yHDJmRKJSHBAa/pz4RCBmWH6coi4gLEn8w5sm7QtGn+JkiYG7utgzIxn+iQzqkFGQjmx77IHirVNW7y5eZI9WG4kJwPc4YIvDnY8bmMnUi+9NPWiwc9w/8/kDA5NBt6qT8+NvINsMuWfmwwmdcorlW3wPOc2GST/ruG12wO5J38u5LDVzTTXZyPtvsGY9Y5u+FRmyFIeGnJP/o/iR31cPLe8xGK8Ca7V8s0rOkquObGa/cqqKZMKtMyjeNfxRmF5psPYDXbE302~-1~-1~-1; bm_sz=C68C3B30CB4BAC2046DCA0C07C3AD7A5~YAAQmnnKF7KFaeaGAQAABDWE9BOoAFSMlLNNE83D2YuuAd6HDhjwA4K8PuRfyu4y3nJ5q78kC+Ph4wKcZUiU25bW6BIemQPnTJSeWGHg3hBCAipEDLf3kkHRhn6+a14KvblItOHei0YdAffHyVkIw362cHn68fdmtu7H/NZDnB0AvNPeECt6iG775p+mD9YajDvnDjgELOoDcftwQpzDNvvMjJ2jcpfX3AlJx6n9KDDjj1j0WelTbsQHhz/lEE8H3OFCjvBqvPhtALpuCOWlH2zjuuSbwgrDrBCUgC+yggPDntizTLuLCllgOtdhATk7dMXQtu+uEx+clI940SCkiYFqan9HieI5QNPOLHsPzej1LDve+cvo/JINoDI6Wsz/xu12E6ceXA==~4470067~4605492'
And the response for that is:
{ "errors": [ { "message": "Cannot read properties of undefined (reading 'operation')" } ] }
Can you help me out?

**Comment by mrt1m** [comment]
You can import my [postman collection](https://github.com/mrt1m/playstation-store-api/blob/main/postman_collection/playstation%20api.postman_collection.json) and try your case

**Comment by vulovicv23** [comment]
This is looking good, thanks!

One more thing, I need to filter only for the full games and dlcs, is it possible to do through the CategoryGrid?

Thanks!

**Comment by mrt1m** [comment]
Unfortunately, I didn't find such an option for the CategoryGrid 
And I can't find special category id for dlcs or add-ons
😢😢😢

**Comment by vulovicv23** [comment]
And what about sending multiple Ids to get more data in one call? So basically, if I Need to get prices, can I send multiple game ids to get multiple prices in one go?

Thanks!

**Comment by whagency** [comment]
Hi, if anyone needs it, I found a category ID to get a list of concepts in the categoryGridRetrieve method with all products, rather than requesting concepts one by one. Here is an example request:

https://web.np.playstation.com/api/graphql/v1/op?operationName=categoryGridRetrieve&variables={"id":"28c9c2b2-cecc-415c-9a08-482a605cb104","pageArgs":{"size":24,"offset":0},"sortBy":null,"filterBy":[],"facetOptions":["ageRating","conceptGenres","conceptReleaseDate","conceptVrCompatibility","webBasePrice","productGenres","productReleaseDate","productVrCompatibility","storeDisplayClassification","targetPlatforms"],"maxResults":null}&extensions={"persistedQuery":{"version":1,"sha256Hash":"4ce7d410a4db2c8b635a48c1dcec375906ff63b19dadd87e073f8fd0c0481d35"}}

**Comment by whagency** [comment]
Please advise me how best to deal with the temporary blocking error - connect: connection refused? I tried a 60 second timeout, but it doesn't help for long.

**Comment by mrt1m** [comment]
Hi @vulovicv23 
Unfortunately, I don't know about this possibility yet.

**Comment by mrt1m** [comment]
Hi @whagency 
I add your category ID to src/Enum/CategoryEnum.php
#8

**Comment by nhung-le** [comment]
> Hi, if anyone needs it, I found a category ID to get a list of concepts in the categoryGridRetrieve method with all products, rather than requesting concepts one by one. Here is an example request:
> 
> [https://web.np.playstation.com/api/graphql/v1/op?operationName=categoryGridRetrieve&variables={"id":"28c9c2b2-cecc-415c-9a08-482a605cb104","pageArgs":{"size":24,"offset":0},"sortBy":null,"filterBy":[],"facetOptions":["ageRating","conceptGenres","conceptReleaseDate","conceptVrCompatibility","webBasePrice","productGenres","productReleaseDate","productVrCompatibility","storeDisplayClassification","targetPlatforms"],"maxResults":null}&extensions={"persistedQuery":{"version":1,"sha256Hash":"4ce7d410a4db2c8b635a48c1dcec375906ff63b19dadd87e073f8fd0c0481d35"}}](https://web.np.playstation.com/api/graphql/v1/op?operationName=categoryGridRetrieve&variables=%7B%22id%22:%2228c9c2b2-cecc-415c-9a08-482a605cb104%22,%22pageArgs%22:%7B%22size%22:24,%22offset%22:0%7D,%22sortBy%22:null,%22filterBy%22:%5B%5D,%22facetOptions%22:%5B%22ageRating%22,%22conceptGenres%22,%22conceptReleaseDate%22,%22conceptVrCompatibility%22,%22webBasePrice%22,%22productGenres%22,%22productReleaseDate%22,%22productVrCompatibility%22,%22storeDisplayClassification%22,%22targetPlatforms%22%5D,%22maxResults%22:null%7D&extensions=%7B%22persistedQuery%22:%7B%22version%22:1,%22sha256Hash%22:%224ce7d410a4db2c8b635a48c1dcec375906ff63b19dadd87e073f8fd0c0481d35%22%7D%7D)

Hello, where did you find `categoryGridRetrieve` operation in the official website, in case I need to refresh my sha256Hash, I can't find anywhere on official website they keep calling to `operationName=queryOracleUserProfileFullSubscription`
