### ISSUE TITLE
This operation has been blocked as a potential Cross-Site Request Forgery (CSRF)

### ISSUE THREAD

**Issue by Prihod** [mrt1m/playstation-store-api#11]
Hi, any request to the api returns an error
`This operation has been blocked as a potential Cross-Site Request Forgery (CSRF). Please either s (truncated...)`

**Comment by mrt1m** [comment]
Hi
Thanks for telling me about the problem

These headings helped me, I will try to release a new version with changes soon.

```php
$client = new Client(
    RegionEnum::UNITED_STATES,
    new HTTPClient([
        'base_uri' => API_URL,
        'timeout' => 5,
        'headers' => [
            'content-type' => 'application/json',
            'origin' => 'https://store.playstation.com'
        ],
    ])
);
```

**Comment by mrt1m** [comment]
@Prihod 
If you notice any other problems, please let me know. I will try to fix them as soon as possible.

**Comment by Prihod** [comment]
> Hi, @Prihod
> 
> Thanks for telling me about the problem
> 
> These headings helped me, I will try to release a new version with changes soon.
> 
> ```
> $client = new Client(
>     RegionEnum::UNITED_STATES,
>     new HTTPClient([
>         'base_uri' => API_URL,
>         'timeout' => 5,
>         'headers' => [
>             'content-type' => 'application/json',
>             'origin' => 'https://store.playstation.com'
>         ],
>     ])
> );
> ```
Thank you, it's working

**Comment by Prihod** [comment]
New error

`cURL error 35: error:0A000119:SSL routines::decryption failed or bad record mac (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://web.np.playstation.com/api/graphql/v1/op?operationName=metGetProductById`
