### ISSUE TITLE
About request signing

### ISSUE THREAD

**Issue by yduke** [mrt1m/playstation-store-api#12]
First of all, good job.

But I was a little bit cofused when I read the ReadMe.md part 5:
[
About request sign](https://github.com/mrt1m/playstation-store-api?tab=readme-ov-file#5-about-request-signing)

Which url to put into browser?  Tried store.playstaion.com homepage, single game page, which is better? 

There are 4 or 5 `/api/graphql/v1/op?` request in single game page, and thire prameter `operationName` is different, like:
> queryOracleUserProfileFullSubscription
> wcaConceptStarRatingRetrive
> queryRetrieveTelemetryDataPDPConcept
> conceptRetrieveForCtasWithPrice
> ....

and each of their 256hash is different, which one should I choose?

If I just want to use getConceptByID and I guess the default hash is here:
https://github.com/mrt1m/playstation-store-api/blob/f2eb4e51a509644f58796218e215e38784221206/src/Enum/OperationSha256Enum.php#L18
How can I get a new 256hash code for that?

Thank you.

**Comment by mrt1m** [comment]
Hi
It seems to me that the method has changed from metGetConceptById to conceptRetrieveForCtasWithPrice

But for an example of a new method the following steps

1) I went to the page https://store.playstation.com/en-us/pages/latest

2) I opened the network window in Google Chrome

3) I click on the banner Spiderman for example 
<img width="728" alt="image" src="https://github.com/user-attachments/assets/32d85abc-2c28-4398-a194-00a641d268a0">

4) I saw a request in the tab
``https://web.np.playstation.com/api/graphql/v1/op?operationName=conceptRetrieveForCtasWithPrice&variables=%7B%22conceptId%22%3A%2210002456%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22eab9d873f90d4ad98fd55f07b6a0a606e6b3925f2d03b70477234b79c1df30b5%22%7D%7D
``

<img width="759" alt="image" src="https://github.com/user-attachments/assets/13cbc566-3772-4d82-86e0-7ae79391b84b">

5) I decode the link through this site https://www.urldecoder.org/ for example and I see
``
https://web.np.playstation.com/api/graphql/v1/op?operationName=conceptRetrieveForCtasWithPrice&variables={"conceptId":"10002456"}&extensions={"persistedQuery":{"version":1,"sha256Hash":"eab9d873f90d4ad98fd55f07b6a0a606e6b3925f2d03b70477234b79c1df30b5"}}
``

6) Now I know that my sha256Hash is eab9d873f90d4ad98fd55f07b6a0a606e6b3925f2d03b70477234b79c1df30b5

If there is no such request, you can create it as described in the readme https://github.com/mrt1m/playstation-store-api?tab=readme-ov-file#6-custom-request

**Comment by mrt1m** [comment]
Now I can't remember where I found the other queries, as the name of the operations may have changed and some pages no longer exist (｡•́︿•̀｡)
