### ISSUE TITLE
Issue with pagination

### ISSUE THREAD

**Issue by volkar1** [mrt1m/playstation-store-api#3]
I'm using code from your example:
```
$client = new Client(RegionEnum::UNITED_STATES, new HTTPClient(['base_uri' => env('PSN_API_URL'), 'timeout' => 5]));
$result = $client->get(
    RequestProductList::createFromCategory(CategoryEnum::OFFERS)
);

$products_list = $result['data']['categoryGridRetrieve']['products'];
```

 And I can see you are using some custom pagination in RequestProductList.php:
```
public static function createFromCategory(CategoryEnum $categoryEnum): RequestProductList
{
    return new self(
        $categoryEnum->value,
        new Pagination(10),
        Sorting::createFromCatalogSorting(CatalogSortingEnum::RELEASE_DATE)
    );
}
```

Is there a way to change pages or is it just stuck on first page? If there is, could you update example files, and documentation?

**Comment by mrt1m** [comment]
I hope these examples can help you
- [examples/get_catalog_pagination_last_page.php](https://github.com/mrt1m/playstation-store-api/blob/main/examples/get_catalog_pagination_last_page.php)
- [examples/get_catalog_pagination_next_page.php](https://github.com/mrt1m/playstation-store-api/blob/main/examples/get_catalog_pagination_next_page.php)
